import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "@/Provider/RootProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col bg-white">
        <RootProvider>
        {children}
        </RootProvider>
        </body>
    </html>
  );
}
